version: '3.9'
services:
  web:
    build:
      context: .
      args:
        build_env: local
        REACT_APP_PUBLIC_URL: http://localhost:3000
        REACT_APP_API_URL: http://localhost:5000/api/v1/
    ports:
      - "3000:80"
